Proc_macro client impls and generate functionality
zingolabs/zcashrpc pull request #11
Opened 2020-09-15 18:15 UTC by AloeareV

2020-09-18 16:32 UTC, zancas commented
Is this still the thing I should review first, or should I look at the other PR?

2020-09-22 01:01 UTC, zancas requested changes

2020-09-22 01:01 UTC, zancas commented on zcashrpc-macros/src/lib.rs
> +        typed_args.stream().into_iter().step_by(4).collect();
I am in agreement about replacing the magical `step_by`, with something more explicit, and renaming `untyped_args_as_stream`.

2020-09-22 19:56 UTC, AloeareV commented on zcash-rcli/src/commands.rs
> +                        $crate::commands::make_client(true).$rpc_call($($(self.$arg),+)?);
Correct

2020-09-24 16:26 UTC, AloeareV commented
This is made obsolete by pr #13. Closing.

2020-09-24 16:26 UTC, closed without merging