Factored logic out of smoke-tests into utils crate, some of it feature gated
zingolabs/zcashrpc pull request #2
Opened 2020-09-02 17:51 UTC by AloeareV

Moved some logic into `zcashrpc::client::utils`. Unfortunately, the file system stuff should be feature-gated as it adds a dependency, and there's no way to make default features specific to tests. Added some conditional logic to the smoke tests to compensate.

2020-09-02 19:22 UTC, zancas requested changes

2020-09-02 19:22 UTC, zancas commented on src/client/utils.rs
> +pub fn get_zcashd_port() -> String {
Of course...   we'll want to paramtrize this soon..
For example, that particular port is `regtest` specific.

2020-09-02 19:22 UTC, zancas commented on tests/zcashrpc-smoke-tests.rs
> +    cfg_if::cfg_if! {
Does this mean I have to pass the `cookie-finder` flag every time I run the smoke tests?!

2020-09-02 19:32 UTC, AloeareV commented on src/client/utils.rs
> +pub fn get_zcashd_port() -> String {
Aha! Yes, that's soon on my list

2020-09-02 19:35 UTC, AloeareV commented on tests/zcashrpc-smoke-tests.rs
> +    cfg_if::cfg_if! {
Unfortunately, yes.. Unless you're using the environment variable. There's no way to make tests automatically use non-default features

2020-09-03 16:04 UTC, AloeareV commented
Made obsolete by #3.

2020-09-03 16:04 UTC, closed without merging