Get cookie takes regtest bool arg
zingolabs/zcashrpc pull request #3
Opened 2020-09-03 15:55 UTC by AloeareV

2020-09-08 23:58 UTC, zancas requested changes

2020-09-08 23:58 UTC, zancas commented on src/client/utils.rs
> +    let mut cookie_file = std::fs::File::open(cookie_path)?;
This line returns with an important error.  There's an inner error, that is wrapped by an outer error.  The inner error tells the proximal reason for the failure.

In a slightly different direction, I would argue that we've already potentially evaluated a bunch of code with an incorrect assumption.

Because I think we should remove all conditional handling of `REGTEST` I'm not going to  drill down on the error chaining potential present here.

2020-09-08 23:58 UTC, zancas commented on src/client/utils.rs
> +pub fn get_zcashd_port() -> String {
We should probably define a `load_config` fn.

It should return a config object..  something like this:

```Rust
struct ConfigOptions {
    w: Option<bool>,
    t: Option<String>
}
struct ZcashRPCError{}
use std::collections::HashMap;
fn load_config() -> Result<ConfigOptions, ZcashRPCError> {
    Ok(ConfigOptions{w: Some(true), t: None})
}
```

This approach lets us leverage Rust's strong types pretty close to where the data is first ingested into the program.   

Probably `abscissa` has a reasonable solution for this.  We should look into that.

Popping out a layer...   the `zcashrpc smoke tests` should assume the existence of a (regtest) zcashd instance in the same permission space.   They should read the zcashd instance's configuration from the expected locations, and add its own (zcashrpc smoketest instance) configuration to the configuration object.

Again we should start by investigating how `abscissa` accomplishes this stuff.

Now that test-instance can be configured in the correct way (with a _per_ _test_ granularity), since each test adds its own config to the baseline config, in a way that doesn't mutate the baseline.

Maybe there's an `Option<TestConfig>` in the `ConfigOptions`...  I dunno'.

2020-09-08 23:58 UTC, zancas commented on src/client/utils.rs
> +    String::from("127.0.0.1:18232")
So, I _think_ both the host and the port should be read from `zcashd` configs (or we could have an interesting pair of tests where one test reads from one source, and another reads from another!).   I'm not clear on the best internal interface to the `ConfigOptions` type?  What's the best pattern there?   A `trait`?

Maybe we could start with an inherent implementation, and only evolve into a `trait` when there's an obvious reason to?

2020-09-09 15:34 UTC, AloeareV commented on tests/zcashrpc-smoke-tests.rs
> +                std::env::var("REGTEST").is_ok()
Changed, now assumes regtest (pending my push to github remote)

2020-09-09 15:34 UTC, AloeareV commented on src/client/utils.rs
> +    let mut cookie_file = std::fs::File::open(cookie_path)?;
Not gonna worry about this at the moment, as I'm assuming regtest

2020-09-09 15:36 UTC, AloeareV commented on src/client/utils.rs
> +pub fn get_zcashd_port() -> String {
Abscissa has some functionality for default configs, reading from a config file, and using command line flags to override the file specs. I remember it looking straight-forward, but I didn't look under the hood very much. Not worrying about this atm, want to get this merged in and then merge zcash-rcli in

2020-09-09 15:37 UTC, AloeareV commented on src/client/utils.rs
> +    String::from("127.0.0.1:18232")
I do think it should be a simple matter of parsing a few lines from the `~/.zcash/zcash.conf` file, yeah

2020-09-09 16:02 UTC, zancas commented on src/client/utils.rs
> +    cookie_path.push(".zcash");
Let's take out this code.
This `fn` should not have a parameter.
There should be no `if`
After we get the home dir:

`cookie_path.push(".zcash").push("regtest").push(".cookie")`

We want to incorporate the simplest working code that we can.

2020-09-09 16:07 UTC, AloeareV commented on src/client/utils.rs
> +    cookie_path.push(".zcash");
Hang on: I think we want this function to be usable for non-regtest. It makes sense to cut it out of the smoke tests, but it's functionality that we want in the library, I think.

2020-09-09 16:11 UTC, zancas commented on src/client/utils.rs
> +    cookie_path.push(".zcash");
Good point.  I agree.

2020-09-09 16:17 UTC, merged