Zcashrpc typegen
zingolabs/zcashrpc pull request #38
Opened 2020-10-22 20:11 UTC by AloeareV

2020-10-23 22:37 UTC, zancas requested changes

2020-10-23 22:37 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
> +    cmd: &GenerateCmd,
Can we add doc comments explaining what this is for?

2020-10-23 22:37 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
> +    cmd: &GenerateCmd,
Is this to read in config?   The name doesn't help me.

2020-10-23 22:37 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
> +    let file_name = file.file_name().to_string_lossy().to_string();
I believe there is a `serde` API that takes a File, or Path, or some such, and returns something like:

`Result<serde_json::Value...`

We should outsource as much file-handling etc, to high profile libraries like `serde`, as we can...

2020-10-23 22:37 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
> +    let file_name = file.file_name().to_string_lossy().to_string();
So, we should be deserializing from a file, or path, instead of a str.

2020-10-23 22:37 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
> +fn sort_and_iter(
Why lump `into_iter` in this function?   Can't the caller call `into_iter` on the result if that's their pleasure?

Maybe we could name this fn `sort_by_string`?

2020-10-23 22:37 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
> +fn typegen(
This seems specific to `serde_json::Map`.

2020-10-23 22:37 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
> +    data: serde_json::Value,
It seems like we might need more specific fn...  one for each of the variants we might alias.    The data should not allow a `serde_json` `Map`.

2020-10-23 22:37 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
> +        pub type #name: $type_body;
Why is there a "$" here?

2020-10-23 22:37 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
>          serde_json::Value::Number(_) => quote::quote!(rust_decimal::Decimal),
Eventually we'll want a rust_decimal type that has a specific precision.

2020-10-26 19:03 UTC, AloeareV commented on Cargo.toml
> -doc = true
There's a special fancy command that allows one to doc the tests, but I can't remember it, and this line breaks the normal cargo doc command. I'd be happy to add it in in conjunction with a doc script.

2020-10-26 19:05 UTC, AloeareV commented on zcashrpc-typegen/Cargo.toml
> +serde_json = "*"
I don't like *, I threw it in because it was a fast way of just throwing the import in and getting it to work without having to look up version numbers. I intend to remove this before I undraft the PR.

2020-10-26 19:05 UTC, AloeareV commented on zcashrpc-typegen/src/commands.rs
> -
No. I've removed all but the version test. Clearly this isn't ideal, we should get tests that actually work at some point.

2020-10-26 19:07 UTC, AloeareV commented on zcashrpc-typegen/src/commands/generate.rs
> +    cmd: &GenerateCmd,
This is to allow me to use `?`, and pass the errors out to a handler. Right now all we do with an error is print to stdout. A much better name would be `try_run`.

2020-10-26 19:15 UTC, AloeareV commented on zcashrpc-typegen/src/commands/generate.rs
> +    let file_name = file.file_name().to_string_lossy().to_string();
There is `https://docs.serde.rs/serde_json/fn.from_reader.html`, however, the documentation mentioned that it's preferable to read the file into memory as a string and call `from_str` on it, as the `from_reader` function is almost 100x less efficient. There's an open issue `https://github.com/serde-rs/json/issues/160`.

2020-10-26 19:19 UTC, AloeareV commented on zcashrpc-typegen/src/commands/generate.rs
> +fn sort_and_iter(
I think that's an artifact, and the original version of this turned it into an iterator, did a couple things to it, and returned it, and so having it return a Vec would be an extra conversion and a conversion right back. That's no longer the case, I'll fix it.

2020-10-26 19:23 UTC, AloeareV commented on zcashrpc-typegen/src/commands/generate.rs
> +        pub type #name: $type_body;
Typo. Fixed in a later commit.

2020-10-26 19:23 UTC, AloeareV commented on zcashrpc-typegen/src/commands/generate.rs
> +    data: serde_json::Value,
That seems like we'd be turning a single match statement into a match statement at every call site. Could we instead return a `Result`, and throw an error if we're passed a match?

2020-10-26 19:25 UTC, AloeareV commented on zcashrpc-typegen/src/commands/generate.rs
> +fn typegen(
Yes, we should only be generating struct item declarations for `Object`s.

2020-10-26 19:25 UTC, AloeareV commented on zcashrpc-typegen/src/commands/generate.rs
>          serde_json::Value::Number(_) => quote::quote!(rust_decimal::Decimal),
I haven't looked into `rust_decimal` much, does it support a precision specifier?

2020-11-04 23:22 UTC, zancas commented on zcashrpc-typegen/tests/acceptance.rs
> +/// the runner acquire a mutex when executing commands and inspecting
So the reason to do this instead of forcing cargo test to run in single threaded mode?

2020-11-04 23:54 UTC, zancas commented on zcashrpc-typegen/src/commands.rs
> -
That's my priority!

2020-11-04 23:55 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
> +    let file_name = file.file_name().to_string_lossy().to_string();
Hmmm...   we don't care about efficiency.

2020-11-04 23:56 UTC, zancas commented on zcashrpc-typegen/src/config.rs
> +            input: Box::from(std::path::Path::new("../json_data")),
Do we really need defaults?

2020-11-05 00:17 UTC, zancas commented on zcashrpc-typegen/src/commands/generate.rs
>          serde_json::Value::Number(_) => quote::quote!(rust_decimal::Decimal),
I think I recall that..

2021-02-22 20:16 UTC, closed without merging