Create typegen-test.yml
zingolabs/zcashrpc pull request #40
Opened 2020-11-12 22:35 UTC by AloeareV

Add CI to run `cargo build`, `cargo test`, and `cargo run -- generate` for `zcashrpc-typegen`. Will not test `zcashrpc` or `zcash-rcli` as they depend on running instance of regtest zcashd, which will prove more difficult to set up.

2020-11-12 22:36 UTC, AloeareV commented
Well, this needs more work. Uh. I think I'm about done for tonight, hopefully by next time I can at least get `cd` working

2020-11-18 20:39 UTC, dannasessha commented
Good we're getting tests going!

Bumping.

2020-11-18 20:40 UTC, dannasessha commented
Once landed, this should solve issue #29.

2020-11-21 04:25 UTC, AloeareV commented
So: The tests fail.. Because of the error we already know about, the one that we can fix by getting rid of the `*` in favor of explicitly using tokio version `0.2.22`. I vote we merge this, afaict it's set up to run the tests against a running regtest zcashd instance.

2020-11-21 16:39 UTC, zancas requested changes

2020-11-21 16:39 UTC, zancas commented on .github/workflows/zcashrpc-test.yml
> +    types: [ assigned, opened, synchronize, reopened ]
I haven't drilled all the way down yet, but from a cursory inspection of this:

https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/github-event-types#pullrequestevent

I wonder if we should trigger on "assigned" and "synchronized"?

2020-11-21 16:39 UTC, zancas commented on .github/workflows/zcashrpc-test.yml
> +    - name:  Authenticate Github CR
"CR"?

2020-11-21 16:39 UTC, zancas commented on .github/workflows/zcashrpc-test.yml
> +        PAT: ${{ secrets.CONTAINER_REGESTRY_READ }}
Typo:   "REGESTRY" --> "REGISTRY"?

2020-11-21 16:39 UTC, zancas commented on .github/workflows/zcashrpc-test.yml
> +      run: echo $PAT | docker login ghcr.io -u USERNAME --password-stdin
Can we switch to token-based or better `ssh`-based login?

2020-11-21 16:45 UTC, AloeareV commented on .github/workflows/zcashrpc-test.yml
> +    types: [ assigned, opened, synchronize, reopened ]
I'm.. Not entirely sure. I'll look into this further.

2020-11-21 16:45 UTC, AloeareV commented on .github/workflows/zcashrpc-test.yml
> +    - name:  Authenticate Github CR
Container Registry

2020-11-21 16:45 UTC, AloeareV commented on .github/workflows/zcashrpc-test.yml
> +        PAT: ${{ secrets.CONTAINER_REGESTRY_READ }}
Ah. Yes. I think I can fix this easily enough

2020-11-21 16:46 UTC, AloeareV commented on .github/workflows/zcashrpc-test.yml
> +      run: echo $PAT | docker login ghcr.io -u USERNAME --password-stdin
The github container registry is in open beta, and as of yet only supports personal access token and password based login.

2020-11-21 20:46 UTC, zancas commented on .github/workflows/zcashrpc-test.yml
> +        PAT: ${{ secrets.CONTAINER_REGESTRY_READ }}
Can you resolve this conversation, or do I have to?   Or is it configurable?

2020-11-21 20:46 UTC, zancas commented on .github/workflows/zcashrpc-test.yml
> +      run: echo $PAT | docker login ghcr.io -u USERNAME --password-stdin
What are the tradeoffs between Personal Access Tokens and Passwords?   I have a notion that PATs are more secure but I'd like to discuss it.

2020-11-21 20:51 UTC, AloeareV commented on .github/workflows/zcashrpc-test.yml
> +        PAT: ${{ secrets.CONTAINER_REGESTRY_READ }}
I can, I will once I fix it!

2020-11-21 20:53 UTC, AloeareV commented on .github/workflows/zcashrpc-test.yml
> +      run: echo $PAT | docker login ghcr.io -u USERNAME --password-stdin
The PAT is limited to read only access to my container registry, whereas a password would have full account access.

2020-11-25 19:03 UTC, zancas approved these changes

2020-11-25 19:29 UTC, merged