Parse flags
zingolabs/zcashrpc pull request #5
Opened 2020-09-09 16:24 UTC by AloeareV

Biiiig batch of Abscissa coming in

2020-09-09 17:18 UTC, zancas requested changes

2020-09-09 17:18 UTC, zancas commented on .gitignore
> +**/*.rs.bk
Huh...    is a tool creating these files?  Or is this specific to something in your flow?

2020-09-09 17:18 UTC, zancas commented on Cargo.toml
> +members = ["zcash_rcli"]
Can this be `"zcash-rcli"`?

2020-09-09 17:19 UTC, zancas commented on zcash_rcli/Cargo.toml
> +name = "zcash_rcli"
Can this be `zcash-rcli`?

2020-09-09 17:21 UTC, AloeareV commented on .gitignore
> +**/*.rs.bk
A tool.

2020-09-09 17:21 UTC, zancas commented on zcash_rcli/Cargo.toml
> +gumdrop = "0.7"
I thought `abscissa` depended on this...  but it's _also_ necessary to depend on it directly?!  :(

2020-09-09 17:22 UTC, zancas commented on zcash_rcli/Cargo.toml
> +# optional: use `gimli` to capture backtraces
Why do we have this comment here?

2020-09-09 17:22 UTC, AloeareV commented on Cargo.toml
> +members = ["zcash_rcli"]
It can, I don't like to use dashes because it can lead to inconsistencies with module names in a way I personally find confusing.

2020-09-09 17:22 UTC, AloeareV commented on zcash_rcli/Cargo.toml
> +gumdrop = "0.7"
Yeah, we directly use it's `Options` command line parsing stuff

2020-09-09 17:23 UTC, AloeareV commented on zcash_rcli/Cargo.toml
> +gumdrop = "0.7"
Although it's possible all the functionality we need is in reexports.

2020-09-09 17:23 UTC, AloeareV commented on zcash_rcli/Cargo.toml
> +# optional: use `gimli` to capture backtraces
It was generated with the `abscissa new` or whatever command, didn't bother to remove it because it's potentially useful to remember.

2020-09-09 17:28 UTC, zancas commented on Cargo.toml
> +members = ["zcash_rcli"]
I think `-` is more consistent both with `zcash-cli` the tool we're replacing, and names on `crates.io`.   Where is it necessary to use `_`?

2020-09-09 17:29 UTC, zancas commented on zcash_rcli/Cargo.toml
> +gumdrop = "0.7"
If it _is_ reexported...  then maybe we should use the `abscissa` version?

2020-09-09 17:30 UTC, zancas commented on zcash_rcli/Cargo.toml
> +# optional: use `gimli` to capture backtraces
OK...  so it's generated...  hmm..  interesting.

2020-09-10 04:49 UTC, zancas commented on zcash_rcli/src/application.rs
> +pub static APPLICATION: AppCell<ZcashRcliApp> = AppCell::new();
The important bit is that this is a "write once" value.

2020-09-10 04:51 UTC, zancas commented on zcash_rcli/src/application.rs
> +pub fn app_reader() -> application::lock::Reader<ZcashRcliApp> {
Can only succeed _after" call to `app_writer` has succeeded.

2020-09-10 05:14 UTC, merged