Implemented generate call for zcashrpc and zcash-rcli
zingolabs/zcashrpc pull request #7
Opened 2020-09-14 19:27 UTC by AloeareV

2020-09-14 20:00 UTC, zancas requested changes

2020-09-14 20:00 UTC, zancas commented on src/client.rs
> +macro_rules! define_rpcs {($($call:ident $camel_call_resp:ident$(($($arg:ident: $type:ty),+))?),+ ) =>
Let's delimit with something more explicit that ` `.   This is a list of calls so the natural delimiter is `, `.

2020-09-14 20:00 UTC, zancas commented on src/client.rs
> +    {$(pub fn $call(
Making the caller repeat themselves to say:  "call" and then "camel_call_resp" feels like an antipattern to me.

It's repetition, and the one is immediately derive-able from the other, so it should be done in code.

One caveat, is that I'd _like_ to derive the CamelCallResponse from the `call` so that we can parse the input out of e.g. `zcash-cli help`..   but we can hack that up later.

2020-09-14 20:00 UTC, zancas commented on src/client/callrpc.rs
> +                    match serde_json::to_value($arg) {
This is totally sweet!

2020-09-14 20:00 UTC, zancas commented on zcash-rcli/src/commands.rs
> +                #[options(free)]
Uhh...   is this a `gumdrop` thing?  'will find out...

2020-09-14 20:00 UTC, zancas commented on zcash-rcli/src/commands.rs
> +                        $crate::commands::make_client(true).$rpc_call($($(self.$arg),+)?);
Nice!

2020-09-14 20:00 UTC, zancas commented on zcash-rcli/src/commands.rs
> +run_impl!(
The caller shouldn't have to repeat themselves.

2020-09-15 19:21 UTC, AloeareV commented
Made obsolete by #11

2020-09-15 19:21 UTC, closed without merging